import Head from "next/head";
import Message from "../components/message";
import { auth } from "../utils/firebase";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { async } from "@firebase/util";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";
import { BiComment } from "react-icons/bi";
import { doc } from "firebase/firestore";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  const route = useRouter();
  const [user, loading] = useAuthState(auth);

  //check if user is loged
  const getData = async () => {
    if (loading) return;
    if (!user) return route.push("/auth/login");
  };
  useEffect(() => {
    getData();
  }, [user, loading]);

  //get posts
  const getPosts = async () => {
    const collectionRef = collection(db, "fullstackdb");
    const q = query(collectionRef, orderBy("timeStamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };
  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full py-6 dark:bg-gray-700">
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `${post.id}`, query: { ...post } }}>
              <button className="absolute">
                <BiComment className="relative -top-1 -left-4 h-12 w-11" />
              </button>
            </Link>
          </Message>
        ))}
        <button
          onClick={() => auth.signOut()}
          className="bg-cyan-500 rounded-lg h-14 w-32 text-white"
        >
          Sign out
        </button>
      </div>
    </div>
  );
}
